import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState } from "react";

const Home: NextPage = () => {
  const [imageURL, setImageURL] = useState("");

  const handleUpload = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const fileInput = event.currentTarget.elements.namedItem(
      "file",
    ) as HTMLInputElement;
    if (!fileInput.files || fileInput.files.length === 0) {
      return;
    }
    const formData = new FormData();
    formData.append("file", fileInput.files[0]);

    const response = await fetch("/api/upload", {
      method: "POST",
      body: formData,
    });
    const data = await response.json();
    // Assuming the data contains the path where the image is stored publicly
    setImageURL(data.url);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Next.js on Replit!</h1>

        <p className={styles.description}>Get started by uploading an image</p>

        <form onSubmit={handleUpload}>
          <input type="file" name="file" required />
          <button type="submit">Upload</button>
        </form>

        {imageURL && (
          <div>
            <p>Image uploaded and processed:</p>
            <img
              src={imageURL}
              alt="Processed Image"
              style={{ maxWidth: "100%" }}
            />
          </div>
        )}
      </main>
    </div>
  );
};

export default Home;
